### ISSUE TITLE
Flag to include/exclude lowercase reference alleles

### ISSUE THREAD

**Issue by jeffersonfparil** [jeffersonfparil/poolgen#19]
Although there is no strict convention on lowercase bases in the reference genome fasta sequence, often this refers to highly repetitive or low confidence regions which we may not want to include in downstream analyses.

See commit: 0931c2a0fbd03aeef1fcc543339f781bc439d1fe and merge: 8df4b2e07286db501dd2091c8ce14080982e790c for reference.

**Comment by cjdjpj** [comment]
This may require significant refactoring, since lparse doesn't take in FilterStats as a parameter, and doing so may ruin the compartmentalization, giving it more responsibility than it should. Should lparse be given filtering permissions or somehow move that base characterization step out of lparse?

**Comment by jeffersonfparil** [comment]
We can consider reverting commit https://github.com/jeffersonfparil/poolgen/commit/0931c2a0fbd03aeef1fcc543339f781bc439d1fe, then allowing the lowercase bases pass through lparse then filter from there. What do you think?

**Comment by jeffersonfparil** [comment]
Awesome!
By the way, you may want to run `cargo fmt`, then `cargo fix`, and `cargo test` prior to pushing just to make sure changes are passing the unit tests (which we will need to overhaul at some point).

**Comment by jeffersonfparil** [comment]
Alternatively, you can create a dev branch and push there prior to creating a pull request to invoke github actions for automated tests.

**Comment by cjdjpj** [comment]
Yep, apologies, for some reason part of my code got cut off last pull request. I'm sending another pull with another feature and the fix. I will test compilation in the future.

**Comment by cjdjpj** [comment]
Sorry about the error again. I'm on it. I thought I tested it.

**Comment by jeffersonfparil** [comment]
All good. I think all those errors are on me. There may be a need to create an initialiser method for the structs.

**Comment by cjdjpj** [comment]
Should I update the test cases with the 3 new flags set to false just so that the tests are passed for now? Or just leave it for refactoring in the future?

**Comment by jeffersonfparil** [comment]
You can patch it for now just so have an indication that we are not introducing too many breaking changes.
